#ifndef PLUGIN_H
#define PLUGIN_H

#ifdef _WIN32
#pragma once
#endif

#define SVENINT_DO_STRING(v) #v
#define SVENINT_STRING(v) SVENINT_DO_STRING(v)

#define SVENINT_MAJOR_VERSION 2
#define SVENINT_MINOR_VERSION 0
#define SVENINT_PATCH_VERSION 41

#define SVENINT_MAJOR_VERSION_STRING SVENINT_STRING( SVENINT_MAJOR_VERSION )
#define SVENINT_MINOR_VERSION_STRING SVENINT_STRING( SVENINT_MINOR_VERSION )
#define SVENINT_PATCH_VERSION_STRING SVENINT_STRING( SVENINT_PATCH_VERSION )

#endif // PLUGIN_H